-- ################################################################################
-- # Script: lua/lib/icons.lua
-- # Author: https://github.com/2KAbhishek
-- # Modifications by: Roberto Flores
-- # Email: fq211776@alumno.udb.edu.sv
-- # GitHub: https://github.com/Elixir-Software-Developer/
-- # Version: 1.0
-- # Description: El archivo icons.lua define una colección de iconos
-- #              utilizados en la interfaz de usuario de Neovim. Estos iconos
-- #              se utilizan para mejorar la experiencia visual y facilitar
-- #              la identificación de diferentes elementos en la interfaz.
-- ################################################################################


-- Retornar una tabla con diferentes categorías de iconos
return {
    -- Iconos para diagnósticos
    diagnostics = {
        Error = ' ',
        Hint = '󰠠 ',
        Information = ' ',
        Question = ' ',
        Warning = ' '
    },
    -- Iconos para documentos
    documents = {
        File = ' ',
        FileEmpty = ' ',
        Files = ' ',
        Folder = ' ',
        FolderEmpty = ' ',
        OpenFolder = ' ',
        OpenFolderEmpty = ' ',
        SymLink = ' ',
        SymlinkFolder = ' ',
        Import = ' '
    },
    -- Iconos para Git
    git = {
        Add = ' ',
        AddAlt = ' ',
        Branch = ' ',
        Diff = ' ',
        DiffAlt = ' ',
        Ignore = '◌ ',
        Mod = ' ',
        Octoface = ' ',
        Remove = ' ',
        RemoveAlt = ' ',
        Rename = ' ',
        Repo = ' ',
        Tag = ' ',
        Untrack = ' '
    },
    -- Iconos para tipos de elementos
    kind = {
        Class = ' ',
        Color = ' ',
        Constant = ' ',
        Constructor = '󰈏 ',
        Enum = ' ',
        EnumMember = ' ',
        Event = ' ',
        Field = ' ',
        File = ' ',
        Folder = ' ',
        Function = '󰊕 ',
        Interface = ' ',
        Keyword = ' ',
        Method = ' ',
        Module = '',
        Operator = ' ',
        Property = ' ',
        Reference = ' ',
        Snippet = ' ',
        Struct = ' ',
        Text = ' ',
        TypeParameter = ' ',
        Unit = ' ',
        Value = ' ',
        Variable = ' '
    },
    -- Iconos para tipos de datos
    type = {
        Array = ' ',
        Boolean = '⏻ ',
        Number = ' ',
        Object = ' ',
        String = ' '
    },
    -- Iconos para la interfaz de usuario (UI)
    ui = {
        Arrow = ' ',
        ArrowClosed = ' ',
        ArrowLeft = ' ',
        ArrowOpen = ' ',
        ArrowRight = ' ',
        Bluetooth = ' ',
        Bookmark = ' ',
        Bug = ' ',
        Calendar = ' ',
        Camera = ' ',
        Check = ' ',
        ChevronRight = '',
        Circle = ' ',
        CircleSmall = '● ',
        CircleSmallEmpty = '○ ',
        Clipboard = ' ',
        Close = ' ',
        Code = ' ',
        Collection = ' ',
        Color = ' ',
        Command = ' ',
        Comment = ' ',
        Copilot = ' ',
        CopilotError = ' ',
        Corner = '└ ',
        Dashboard = ' ',
        Database = ' ',
        Download = ' ',
        Edge = '│ ',
        Electric = ' ',
        Eye = ' ',
        Fire = ' ',
        Firefox = ' ',
        Flag = ' ',
        Game = ' ',
        Gear = ' ',
        GitHub = ' ',
        Heart = ' ',
        History = ' ',
        Home = ' ',
        Incoming = ' ',
        Jump = ' ',
        Keyboard = '  ',
        Ligthbulb = '󰌵 ',
        List = '',
        Lock = ' ',
        Minus = '‒ ',
        Music = '󰝚 ',
        Neovim = ' ',
        NewFile = ' ',
        None = ' ',
        Note = ' ',
        Outgoing = ' ',
        Package = ' ',
        Paint = ' ',
        Pause = ' ',
        Pencil = ' ',
        Person = ' ',
        Pin = ' ',
        Play = ' ',
        Plug = ' ',
        Plus = ' ',
        Power = ' ',
        PowerlineArrowLeft = '',
        PowerlineArrowRight = '',
        PowerlineLeftRound = '',
        PowerlineRightRound = '',
        Project = ' ',
        Question = ' ',
        Reload = ' ',
        Rocket = ' ',
        Save = '󰆓 ',
        Search = ' ',
        Separator = '▊ ',
        SeparatorLight = '▍',
        SeparatorDashed = '┆',
        SignIn = ' ',
        SignOut = ' ',
        Sleep = '󰒲 ',
        Star = ' ',
        Table = ' ',
        Telescope = ' ',
        Terminal = ' ',
        Test = ' ',
        Time = ' ',
        Topline = '‾',
        Trash = ' ',
        User = ' ',
        Vim = ' ',
        Wifi = ' ',
        Windows = ' '
    }
}
